# Generated by Django 3.2.9 on 2021-12-07 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AnimalShelter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cats',
            name='breed',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='AnimalShelter.catbreeds'),
        ),
        migrations.AlterField(
            model_name='cats',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='breed',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='AnimalShelter.dogbreeds'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
