# Generated by Django 3.2.9 on 2021-12-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimalShelter', '0002_auto_20211206_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cats',
            name='adopted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cats',
            name='arrived',
            field=models.DateField(auto_now_add=True),
        ),
    ]
