# Generated by Django 3.2.9 on 2021-12-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimalShelter', '0004_auto_20211207_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cats',
            name='adopted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='arrived',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
