# Generated by Django 3.2.9 on 2021-12-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimalShelter', '0006_auto_20211207_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('user_email', models.EmailField(max_length=254)),
                ('employee_email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
